sequenceDiagram
    participant P as Producer
    participant B as Broker
    participant L as Leader Partition
    participant F1 as Follower 1
    participant F2 as Follower 2

    P->>B: Send Record
    activate P
      B->>L: Persist Record
      L-->>B: Record Persisted
      B-->>P: Acknowledge
    deactivate P
    L->>F1: Persist Record
    L->>F2: Persist Record
