sequenceDiagram
    participant P as Producer
    participant B as Broker
    participant P0 as Partition0
    participant P1 as Partition1
    participant P2 as Partition2
    
    P->>+B: Key: UserID_x2342
    B->>-P0: Persist with offset 0
    P->>+B: Key: UserID_x5615
    B->>-P1: Persist with offset 0
    P->>+B: Key: UserID_x8841
    B->>-P1: Persist with offset 1
    P->>+B: Key: UserID_x7741
    B->>-P2: Persist with offset 0
