name: Build and Release PDF

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.7.0"
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Marp CLI
        run: yarn install:marp

      - name: Build PDF presentation
        run: |
          mkdir -p ./dist
          yarn build:pdf

      - name: Get tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Asset
        run: |
          gh release create ${{ steps.get_tag.outputs.TAG_NAME }} \
            --title "Release ${{ steps.get_tag.outputs.TAG_NAME }}" \
            --notes "## Kafka Introduction Presentation

          This release contains the PDF version of the Kafka introduction presentation.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete previous releases
        run: |
          gh release list --limit 10 --json tagName | \
          jq -r '.[].tagName' | \
          grep -v "${{ steps.get_tag.outputs.TAG_NAME }}" | \
          xargs -I {} gh release delete {} --yes || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
